openapi: 3.1.0
info:
  title: NostrRESTGateway
  version: '1.0'
  summary: NostrRESRGateway
  description: Nostr REST API Gateway Server OpenAPISpec
servers:
  - url: 'http://localhost:8080'
    description: Local
paths:
  /v1/users:
    get:
      summary: GET Users Profiles
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/UserResponse'
      operationId: get-v1-users
      description: Specify public keysfor a user to obtain user profile.
      parameters:
        - schema:
            type: string
            minItems: 1
            maxItems: 100
          in: query
          name: pubkey
          description: Public key of the user to retrieve
          required: true
    post:
      summary: GET User Profiles
      operationId: post-v1-users
      responses:
        '200':
          $ref: '#/components/responses/UsersResponse'
      description: |-
        Specify multiple public keys for a user to obtain user profiles.
        (API Endpoint specified in RequestBody. (To avoid URL length limitation))
      requestBody:
        $ref: '#/components/requestBodies/UsersPubKeyRequest'
  /v1/users/following:
    get:
      summary: Get Following Users
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/UsersResponse'
      operationId: get-v1-users-following
      parameters:
        - schema:
            type: string
          in: query
          name: pubkey
          description: Public key of the user
          required: true
      description: Get users followed by the specified user.
  /v1/users/following/pubkeys:
    get:
      summary: Get Following User's PublicKeys
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/PubKeysResponse'
      operationId: get-v1-users-following-pubkeys
      description: Get user's public keys followed by the specified user.
      parameters:
        - schema:
            type: string
          in: query
          name: pubkey
          description: Public key of the user
          required: true
    parameters: []
  /v1/timelines/home:
    get:
      summary: Get Home Timeline
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/PostsResponse'
      operationId: get-v1-timelines-home
      description: Get posts of users that the specified user follows.
      parameters:
        - schema:
            type: string
          in: query
          name: pubkey
          required: true
          description: Public key of the user
  /v1/timelines/user:
    get:
      summary: Get User Timeline
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/PostsResponse'
      operationId: get-v1-timelines-user
      description: Get the posts of the specified user.
      parameters:
        - schema:
            type: string
          in: query
          name: pubkey
          description: Public key of the user
          required: true
components:
  schemas:
    User:
      title: User
      type: object
      examples: []
      properties:
        pubkey:
          type: string
          description: User public key (user idenitifier)
        name:
          type: string
          description: User name
        display_name:
          type: string
          description: User display name
        about:
          type: string
          description: User description
        picture:
          type: string
          description: User icon image url
        banner:
          type: string
          description: User profile banner image url
        website:
          type: string
          description: User website url
      required:
        - pubkey
    Post:
      title: Post
      x-stoplight:
        id: zo0wtfbsq7tq3
      type: object
      properties:
        content:
          type: string
          description: Raw text of post content.
        user:
          $ref: '#/components/schemas/User'
          description: Author of post.
      required:
        - content
        - user
  requestBodies:
    UsersPubKeyRequest:
      content:
        application/json:
          schema:
            type: object
            properties:
              pubkeys:
                type: array
                description: Public key of the user to retrieve
                items:
                  type: string
                  minLength: 1
                  maxLength: 100
            required:
              - pubkeys
          examples:
            Example 1:
              value:
                pubkeys:
                  - 776ea4437354381f14a720be3c476937dce7257ed1073e54a192dbc99f3b7ecc
      description: ''
  responses:
    UsersResponse:
      description: ''
      content:
        application/json:
          schema:
            type: object
            properties:
              list:
                type: array
                description: User list
                items:
                  $ref: '#/components/schemas/User'
              count:
                type: integer
                description: Number of list
            required:
              - list
              - count
    UserResponse:
      description: ''
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User'
    PubKeysResponse:
      description: ''
      content:
        application/json:
          schema:
            type: object
            properties:
              pubkeys:
                type: array
                description: User's PublicKeys
                items:
                  type: string
            required:
              - pubkeys
    PostsResponse:
      description: ''
      content:
        application/json:
          schema:
            type: object
            properties:
              list:
                type: array
                description: Post list
                items:
                  $ref: '#/components/schemas/Post'
              count:
                type: integer
                description: Number of list
            required:
              - list
              - count
